import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/event.dart';
import '../utils/app_dates.dart';

class YearCalendarPdfService {
  static final PdfColor _blue = PdfColor.fromInt(0xFF003F87);
  static final PdfColor _darkBlue = PdfColor.fromInt(0xFF003366);
  static final PdfColor _red = PdfColor.fromInt(0xFFCE1126);
  static final PdfColor _lightRed = PdfColor.fromInt(0xFFFBEAEB);
  static final PdfColor _grey = PdfColor.fromInt(0xFF515354);

  static const List<String> _months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  static const List<String> _letters = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];

  static Future<Uint8List> buildYearCalendar({
    required int year,
    required String troopName,
    Uint8List? logoBytes,
    List<Event> events = const [],
  }) async {
    final byDay = <String, List<Event>>{};
    for (final event in events) {
      final date = event.date;
      if (date == null || date.year != year) continue;
      byDay.putIfAbsent(AppDates.dayKey(date), () => <Event>[]).add(event);
    }

    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.letter.landscape,
        margin: const pw.EdgeInsets.all(24),
        build: (_) => pw.Column(
          children: [
            _header(troopName, year, logoBytes),
            pw.SizedBox(height: 10),
            pw.Expanded(child: _yearGrid(year, byDay)),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by Troop Manager · Scouting America',
                  style: pw.TextStyle(fontSize: 7, color: _grey),
                ),
                pw.Text(
                  '$year Program Calendar',
                  style: pw.TextStyle(fontSize: 7, color: _grey),
                ),
              ],
            ),
          ],
        ),
      ),
    );
    return doc.save();
  }

  static pw.Widget _header(String troopName, int year, Uint8List? logoBytes) {
    return pw.Row(
      children: [
        if (logoBytes != null) ...[
          pw.ClipOval(
            child: pw.Image(
              pw.MemoryImage(logoBytes),
              width: 34,
              height: 34,
              fit: pw.BoxFit.cover,
            ),
          ),
          pw.SizedBox(width: 10),
        ],
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                troopName,
                style: pw.TextStyle(
                  fontSize: 19,
                  fontWeight: pw.FontWeight.bold,
                  color: _blue,
                ),
              ),
              pw.Text(
                'Troop Program Calendar',
                style: pw.TextStyle(fontSize: 9, color: _grey),
              ),
            ],
          ),
        ),
        pw.Text(
          '$year',
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: _red,
          ),
        ),
      ],
    );
  }

  static pw.Widget _yearGrid(int year, Map<String, List<Event>> byDay) {
    return pw.Column(
      children: List.generate(3, (r) {
        return pw.Expanded(
          child: pw.Row(
            children: List.generate(4, (c) {
              final month = r * 4 + c + 1;
              return pw.Expanded(
                child: pw.Padding(
                  padding: const pw.EdgeInsets.all(2),
                  child: _monthColumn(year, month, byDay),
                ),
              );
            }),
          ),
        );
      }),
    );
  }

  static pw.Widget _monthColumn(
      int year, int month, Map<String, List<Event>> byDay) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Container(
          color: _blue,
          padding: const pw.EdgeInsets.symmetric(vertical: 2),
          alignment: pw.Alignment.center,
          child: pw.Text(
            _months[month - 1],
            style: pw.TextStyle(
              fontSize: 9,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
              letterSpacing: 0.4,
            ),
          ),
        ),
        pw.SizedBox(height: 1.5),
        _monthTable(year, month, byDay),
      ],
    );
  }

  static pw.Widget _monthTable(
      int year, int month, Map<String, List<Event>> byDay) {
    final first = DateTime(year, month, 1);
    final startCol = first.weekday % 7;
    final daysInMonth = DateTime(year, month + 1, 0).day;
    final weeks = ((startCol + daysInMonth) / 7).ceil();

    final cells = <int?>[...List<int?>.filled(startCol, null)];
    for (var day = 1; day <= daysInMonth; day++) {
      cells.add(day);
    }
    while (cells.length < weeks * 7) {
      cells.add(null);
    }

    final rows = <pw.TableRow>[
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: List.generate(7, (i) {
          return pw.Container(
            height: 11,
            alignment: pw.Alignment.center,
            child: pw.Text(
              _letters[i],
              style: pw.TextStyle(
                fontSize: 6.5,
                fontWeight: pw.FontWeight.bold,
                color: _darkBlue,
              ),
            ),
          );
        }),
      ),
    ];

    for (var w = 0; w < weeks; w++) {
      rows.add(
        pw.TableRow(
          children: List.generate(7, (col) {
            final day = cells[w * 7 + col];
            if (day == null) {
              return pw.Container(height: 15);
            }
            final isEvent = byDay.containsKey(
              AppDates.dayKey(DateTime(year, month, day)),
            );
            return pw.Container(
              height: 15,
              alignment: pw.Alignment.center,
              decoration: isEvent ? pw.BoxDecoration(color: _lightRed) : null,
              child: pw.Text(
                '$day',
                style: pw.TextStyle(
                  fontSize: 6.5,
                  fontWeight: isEvent ? pw.FontWeight.bold : pw.FontWeight.normal,
                  color: isEvent ? _red : PdfColors.black,
                ),
              ),
            );
          }),
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey, width: 0.3),
      children: rows,
    );
  }
}