import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../models/event.dart';
import '../utils/app_dates.dart';

class YearCalendarPdfService {
  static final PdfColor _blue = PdfColor.fromInt(0xFF003F87);
  static final PdfColor _darkBlue = PdfColor.fromInt(0xFF003366);
  static final PdfColor _red = PdfColor.fromInt(0xFFCE1126);
  static final PdfColor _lightRed = PdfColor.fromInt(0xFFFBEAEB);
  static final PdfColor _grey = PdfColor.fromInt(0xFF515354);

  static const List<String> _months = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December',
  ];
  static const List<String> _shortMonths = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ];
  static const List<String> _letters = ['S', 'M', 'T', 'W', 'T', 'F', 'S'];

  static Future<Uint8List> buildYearCalendar({
    required int year,
    required String troopName,
    Uint8List? logoBytes,
    List<Event> events = const [],
  }) async {
    final yearEvents = events
        .where((e) => e.date != null && e.date!.year == year)
        .toList()
      ..sort((a, b) => a.date!.compareTo(b.date!));
    final byDay = <String, List<Event>>{};
    for (final event in yearEvents) {
      byDay.putIfAbsent(AppDates.dayKey(event.date!), () => <Event>[]).add(event);
    }

    final doc = pw.Document();
    doc.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.letter,
        margin: const pw.EdgeInsets.all(24),
        build: (_) => pw.Column(
          children: [
            _header(troopName, year, logoBytes),
            pw.SizedBox(height: 10),
            pw.Expanded(child: _yearGrid(year, byDay)),
            pw.SizedBox(height: 4),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(
                  'Generated by Troop Manager · Scouting America',
                  style: pw.TextStyle(fontSize: 7, color: _grey),
                ),
                pw.Text(
                  '$year Program Calendar',
                  style: pw.TextStyle(fontSize: 7, color: _grey),
                ),
              ],
            ),
          ],
        ),
      ),
    );

    if (yearEvents.isNotEmpty) {
      doc.addPage(
        pw.MultiPage(
          pageFormat: PdfPageFormat.letter,
          margin: const pw.EdgeInsets.all(24),
          build: (_) => _eventListSections(year, yearEvents),
        ),
      );
    }

    return doc.save();
  }

  static List<pw.Widget> _eventListSections(int year, List<Event> events) {
    final widgets = <pw.Widget>[
      pw.Text(
        '$year Events List',
        style: pw.TextStyle(
          fontSize: 15,
          fontWeight: pw.FontWeight.bold,
          color: _blue,
        ),
      ),
      pw.SizedBox(height: 3),
      pw.Text(
        '${events.length} events · days highlighted in red on the calendar',
        style: pw.TextStyle(fontSize: 8, color: _grey),
      ),
      pw.SizedBox(height: 8),
    ];

    for (var month = 1; month <= 12; month++) {
      final monthEvents =
          events.where((e) => e.date!.month == month).toList();
      if (monthEvents.isEmpty) continue;
      widgets.add(
        pw.Text(
          _months[month - 1],
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: _darkBlue,
          ),
        ),
      );
      widgets.add(pw.SizedBox(height: 3));
      widgets.add(_eventsTable(monthEvents));
      widgets.add(pw.SizedBox(height: 8));
    }
    return widgets;
  }

  static pw.Widget _eventsTable(List<Event> events) {
    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey400, width: 0.4),
      columnWidths: const {
        0: pw.FixedColumnWidth(46),
        1: pw.FlexColumnWidth(3),
        2: pw.FlexColumnWidth(1.4),
        3: pw.FlexColumnWidth(2),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey200),
          children: [
            _cell('Date', bold: true),
            _cell('Event', bold: true),
            _cell('Type', bold: true),
            _cell('Location', bold: true),
          ],
        ),
        for (final event in events)
          pw.TableRow(
            children: [
              _cell(_dateLabel(event.date!)),
              _cell(event.title, bold: true),
              _cell(event.type),
              _cell(event.location),
            ],
          ),
      ],
    );
  }

  static pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2),
      alignment: pw.Alignment.centerLeft,
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 8,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }

  static String _dateLabel(DateTime date) =>
      '${_shortMonths[date.month - 1]} ${date.day}';

  static pw.Widget _header(String troopName, int year, Uint8List? logoBytes) {
    return pw.Row(
      children: [
        if (logoBytes != null) ...[
          pw.ClipOval(
            child: pw.Image(
              pw.MemoryImage(logoBytes),
              width: 34,
              height: 34,
              fit: pw.BoxFit.cover,
            ),
          ),
          pw.SizedBox(width: 10),
        ],
        pw.Expanded(
          child: pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                troopName,
                style: pw.TextStyle(
                  fontSize: 19,
                  fontWeight: pw.FontWeight.bold,
                  color: _blue,
                ),
              ),
              pw.Text(
                'Troop Program Calendar',
                style: pw.TextStyle(fontSize: 9, color: _grey),
              ),
            ],
          ),
        ),
        pw.Text(
          '$year',
          style: pw.TextStyle(
            fontSize: 22,
            fontWeight: pw.FontWeight.bold,
            color: _red,
          ),
        ),
      ],
    );
  }

  static pw.Widget _yearGrid(int year, Map<String, List<Event>> byDay) {
    return pw.Column(
      children: List.generate(4, (r) {
        return pw.Expanded(
          child: pw.Row(
            children: List.generate(3, (c) {
              final month = r * 3 + c + 1;
              return pw.Expanded(
                child: pw.Padding(
                  padding: const pw.EdgeInsets.all(2),
                  child: _monthColumn(year, month, byDay),
                ),
              );
            }),
          ),
        );
      }),
    );
  }

  static pw.Widget _monthColumn(
      int year, int month, Map<String, List<Event>> byDay) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.stretch,
      children: [
        pw.Container(
          color: _blue,
          padding: const pw.EdgeInsets.symmetric(vertical: 2),
          alignment: pw.Alignment.center,
          child: pw.Text(
            _months[month - 1],
            style: pw.TextStyle(
              fontSize: 8,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.white,
              letterSpacing: 0.4,
            ),
          ),
        ),
        pw.SizedBox(height: 1.5),
        _monthTable(year, month, byDay),
      ],
    );
  }

  static pw.Widget _monthTable(
      int year, int month, Map<String, List<Event>> byDay) {
    final first = DateTime(year, month, 1);
    final startCol = first.weekday % 7;
    final daysInMonth = DateTime(year, month + 1, 0).day;
    final weeks = ((startCol + daysInMonth) / 7).ceil();

    final cells = <int?>[...List<int?>.filled(startCol, null)];
    for (var day = 1; day <= daysInMonth; day++) {
      cells.add(day);
    }
    while (cells.length < weeks * 7) {
      cells.add(null);
    }

    final rows = <pw.TableRow>[
      pw.TableRow(
        decoration: const pw.BoxDecoration(color: PdfColors.grey200),
        children: List.generate(7, (i) {
          return pw.Container(
            height: 10,
            alignment: pw.Alignment.center,
            child: pw.Text(
              _letters[i],
              style: pw.TextStyle(
                fontSize: 6,
                fontWeight: pw.FontWeight.bold,
                color: _darkBlue,
              ),
            ),
          );
        }),
      ),
    ];

    for (var w = 0; w < weeks; w++) {
      rows.add(
        pw.TableRow(
          children: List.generate(7, (col) {
            final day = cells[w * 7 + col];
            if (day == null) {
              return pw.Container(height: 14);
            }
            final isEvent = byDay.containsKey(
              AppDates.dayKey(DateTime(year, month, day)),
            );
            return pw.Container(
              height: 14,
              alignment: pw.Alignment.center,
              decoration: isEvent ? pw.BoxDecoration(color: _lightRed) : null,
              child: pw.Text(
                '$day',
                style: pw.TextStyle(
                  fontSize: 6,
                  fontWeight: isEvent ? pw.FontWeight.bold : pw.FontWeight.normal,
                  color: isEvent ? _red : PdfColors.black,
                ),
              ),
            );
          }),
        ),
      );
    }

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey, width: 0.3),
      children: rows,
    );
  }
}